# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-01"

[[extensions]]
name = "Customer Toggle tag"
handle = "customer-toggle-tag"
type = "ui_extension"
uid = "0049211e-496b-8c7e-6d0b-b30ba6a2c0f87172d233"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#network-access
# network_access = true

[extensions.settings]
 [[extensions.settings.fields]]
  key = "label_checkbox"
  type = "single_line_text_field"
  name = "Checkbox label"
  description = "Enter a label for the checkbox."
  default = "Click de nhan bat ngo!"

  [[extensions.settings.fields]]
  key = "action_description"
  type = "multi_line_text_field"
  name = "Action description"
  description = "Enter a description for the action."
  default = "Lam gi co gi bat ngo dau :D"

  [[extensions.settings.fields]]
    key = "datajet_id_action"
    type = "single_line_text_field"
    name = "Datajet ID action"
    description = "Enter the Datajet ID for the action."